/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.GUI.menu;

import projeto.GUI.mensagem.CadastrarMensagem;
import projeto.GUI.mensagem.ConsultarMensagem;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import projeto.GUI.TelaSobreGeral;
import projeto.GUI.mensagem.CadastrarMensagemCliente;
import projeto.GUI.projetos.CadastrarProjeto_Suporte;
import projeto.GUI.projetos.ProjetosCadastrados_Suporte;
import projeto.GUI.usuario.TelaCadastrarUsuario;
import projeto.GUI.usuario.TelaCadastrarUsuarioAdmin;
import projeto.GUI.usuario.TelaUsuariosCadastrados;
import projeto.Main;
import projeto.model.tipos.FuncaoUsuario;

/**
 *
 * @author jenny
 */
public class MenuPrincipal_Suporte extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal_Suporte() {
        initComponents();
        setTitle("Pro4Tech");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
        public void windowClosing(WindowEvent e){
            Main.getConnectionFactory().closeConnection();
            System.exit(0);
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menu_mensagem = new javax.swing.JMenu();
        menuItem_adicionarMensagem = new javax.swing.JMenuItem();
        menuItem_consultarMensagem = new javax.swing.JMenuItem();
        menu_gerenciar = new javax.swing.JMenu();
        menuItem_adicionarProjetos = new javax.swing.JMenuItem();
        menuItem_projetosCadastrados = new javax.swing.JMenuItem();
        menuItem_cadastrarUsuario = new javax.swing.JMenuItem();
        menuItem_usuarioCadastrado = new javax.swing.JMenuItem();
        menu_sobre = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/pro4tech.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jMenuBar2.setBackground(new java.awt.Color(204, 204, 204));

        menu_mensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/email_attach.png"))); // NOI18N
        menu_mensagem.setText("Mensagens");
        menu_mensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_mensagemActionPerformed(evt);
            }
        });

        menuItem_adicionarMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/+.png"))); // NOI18N
        menuItem_adicionarMensagem.setText("Adicionar");
        menuItem_adicionarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_adicionarMensagemActionPerformed(evt);
            }
        });
        menu_mensagem.add(menuItem_adicionarMensagem);

        menuItem_consultarMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/Lupa.png"))); // NOI18N
        menuItem_consultarMensagem.setText("Consultar");
        menuItem_consultarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_consultarMensagemActionPerformed(evt);
            }
        });
        menu_mensagem.add(menuItem_consultarMensagem);

        jMenuBar2.add(menu_mensagem);

        menu_gerenciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/Engrenagem.png"))); // NOI18N
        menu_gerenciar.setText("Gerenciar");
        menu_gerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_gerenciarActionPerformed(evt);
            }
        });

        menuItem_adicionarProjetos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/+.png"))); // NOI18N
        menuItem_adicionarProjetos.setText("Adicionar Projeto");
        menuItem_adicionarProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_adicionarProjetosActionPerformed(evt);
            }
        });
        menu_gerenciar.add(menuItem_adicionarProjetos);

        menuItem_projetosCadastrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/Lupa.png"))); // NOI18N
        menuItem_projetosCadastrados.setText("Projetos Cadastrados");
        menuItem_projetosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_projetosCadastradosActionPerformed(evt);
            }
        });
        menu_gerenciar.add(menuItem_projetosCadastrados);

        menuItem_cadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/+.png"))); // NOI18N
        menuItem_cadastrarUsuario.setText("Cadastrar Usuários");
        menuItem_cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_cadastrarUsuarioActionPerformed(evt);
            }
        });
        menu_gerenciar.add(menuItem_cadastrarUsuario);

        menuItem_usuarioCadastrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/Lupa.png"))); // NOI18N
        menuItem_usuarioCadastrado.setText("Usuários Cadastrados");
        menuItem_usuarioCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_usuarioCadastradoActionPerformed(evt);
            }
        });
        menu_gerenciar.add(menuItem_usuarioCadastrado);

        jMenuBar2.add(menu_gerenciar);

        menu_sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/exclamation.png"))); // NOI18N
        menu_sobre.setText("Sobre");
        menu_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sobreActionPerformed(evt);
            }
        });
        jMenuBar2.add(menu_sobre);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_adicionarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_adicionarMensagemActionPerformed
     
         new CadastrarMensagemCliente().setVisible(true);
        
    }//GEN-LAST:event_menuItem_adicionarMensagemActionPerformed

    private void menu_mensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_mensagemActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_menu_mensagemActionPerformed

    private void menuItem_consultarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_consultarMensagemActionPerformed
        // TODO add your handling code here:
        
        new ConsultarMensagem().setVisible(true);
    }//GEN-LAST:event_menuItem_consultarMensagemActionPerformed

    private void menu_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sobreActionPerformed
        // TODO add your handling code here:
        new TelaSobreGeral().setVisible(true);
    }//GEN-LAST:event_menu_sobreActionPerformed

    private void menu_gerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_gerenciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_gerenciarActionPerformed

    private void menuItem_adicionarProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_adicionarProjetosActionPerformed
        // TODO add your handling code here:
        new CadastrarProjeto_Suporte().setVisible(true);
    }//GEN-LAST:event_menuItem_adicionarProjetosActionPerformed

    private void menuItem_projetosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_projetosCadastradosActionPerformed
        // TODO add your handling code here:
        new ProjetosCadastrados_Suporte().setVisible(true);
    }//GEN-LAST:event_menuItem_projetosCadastradosActionPerformed

    private void menuItem_cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_cadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        if(Main.getManager().getUsuarioLogado().getFuncaoUsuario() == FuncaoUsuario.SUPORTE.getId()) new TelaCadastrarUsuario().setVisible(true);
        else new TelaCadastrarUsuarioAdmin().setVisible(true);
    }//GEN-LAST:event_menuItem_cadastrarUsuarioActionPerformed

    private void menuItem_usuarioCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_usuarioCadastradoActionPerformed
        // TODO add your handling code here:
        new TelaUsuariosCadastrados().setVisible(true);
    }//GEN-LAST:event_menuItem_usuarioCadastradoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menuItem_adicionarMensagem;
    private javax.swing.JMenuItem menuItem_adicionarProjetos;
    private javax.swing.JMenuItem menuItem_cadastrarUsuario;
    private javax.swing.JMenuItem menuItem_consultarMensagem;
    private javax.swing.JMenuItem menuItem_projetosCadastrados;
    private javax.swing.JMenuItem menuItem_usuarioCadastrado;
    private javax.swing.JMenu menu_gerenciar;
    private javax.swing.JMenu menu_mensagem;
    private javax.swing.JMenu menu_sobre;
    // End of variables declaration//GEN-END:variables
}
