/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.GUI.mensagem;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import projeto.Main;
import projeto.model.Mensagem;

/**
 *
 * @author jenny
 */
public class ConsultarMensagem extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarMensagem
     */
    public ConsultarMensagem() {
        initComponents();
        DefaultTableModel tabelaMensagens =  (DefaultTableModel) jTMensagens.getModel();
        jTMensagens.setRowSorter(new TableRowSorter(tabelaMensagens));
         
        readTable();

        setTitle("Pro4Tech - Consultar mensagens");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_nomeCliente = new javax.swing.JLabel();
        label_responsavelRegistro = new javax.swing.JLabel();
        nomeClienteTextField = new javax.swing.JTextField();
        nomeQuemEnviouTextField = new javax.swing.JTextField();
        button_consultar = new javax.swing.JButton();
        label_iconUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMensagens = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        label_nomeCliente.setText("NOME DO CLIENTE");

        label_responsavelRegistro.setText("RESPONSÁVEL PELO REGISTRO");

        nomeClienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteTextFieldActionPerformed(evt);
            }
        });

        nomeQuemEnviouTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeQuemEnviouTextFieldActionPerformed(evt);
            }
        });

        button_consultar.setText("Consultar ");
        button_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_consultarActionPerformed(evt);
            }
        });

        label_iconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Imagens/User.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_iconUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_nomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeQuemEnviouTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_responsavelRegistro))))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(label_responsavelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nomeCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_iconUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeQuemEnviouTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(button_consultar)
                .addGap(25, 25, 25))
        );

        jTMensagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome do Cliente", "Responsável pelo Registro", "Meio", "Conteúdo", "Data"
            }
        ));
        jTMensagens.setName(""); // NOI18N
        jTMensagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMensagensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTMensagens);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_consultarActionPerformed
        String nomeCliente = nomeClienteTextField.getText();
        String quemEnviou = nomeQuemEnviouTextField.getText();
        
        
//        MensagemDAO mensagemDAO = Main.getManager().getMensagemDAO();
        
        List<Mensagem> listaMensagens = new ArrayList<>();
        
         if ( nomeCliente.isEmpty() == false ) {
//             listaMensagens = mensagemDAO.getMensagensPorCliente(nomeCliente);             
         }else{ 
      
//             listaMensagens = mensagemDAO.getMensagensPorQuemEnviou(quemEnviou);
         }
                
         DefaultTableModel tabelaMensagens =  (DefaultTableModel) jTMensagens.getModel();
         tabelaMensagens.setNumRows(0);
        
        for(Mensagem mensagem: listaMensagens){
//            tabelaMensagens.addRow(new Object[]{
//                mensagem.getNomeCliente(),
//                mensagem.getQuemEnviou(),
//                mensagem.getMeio(),
//                mensagem.getConteudo(),
//                Main.getManager().transformarData(mensagem.getData()).replace("-", "às")
//                });
        }
        
    }//GEN-LAST:event_button_consultarActionPerformed

    private void nomeClienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteTextFieldActionPerformed

    private void nomeQuemEnviouTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeQuemEnviouTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeQuemEnviouTextFieldActionPerformed

    private void jTMensagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMensagensMouseClicked
        // TODO add your handling code here:
                int linhaSelecionada =  jTMensagens.getSelectedRow();
        
         String cliente = (String)jTMensagens.getValueAt(linhaSelecionada, 0);
         String quemEnviou = (String)jTMensagens.getValueAt(linhaSelecionada, 1);
         String meioContato = (String)jTMensagens.getValueAt(linhaSelecionada, 2);
         String mensagem = (String)jTMensagens.getValueAt(linhaSelecionada, 3);
         long horario = (long)Main.getManager().destransformarData((String)jTMensagens.getValueAt(linhaSelecionada, 4));
                 
//        Mensagem mensagemSelecionada = new Mensagem(cliente, quemEnviou, meioContato, mensagem, horario);
        
        
                 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
//                ExibirLinhasTabela exibitExibirLinhasTabela = new ExibirLinhasTabela(mensagemSelecionada);
//                exibitExibirLinhasTabela.setVisible(true);
            }
        });
    }//GEN-LAST:event_jTMensagensMouseClicked

    
    public void readTable(){
        DefaultTableModel tabelaMensagens =  (DefaultTableModel) jTMensagens.getModel();
        
         tabelaMensagens.setNumRows(0);
        
//       List<Mensagem> listaMensagens = Main.getManager().pegarTodasMensagens();
        
//        for(Mensagem mensagem: listaMensagens){
//            tabelaMensagens.addRow(new Object[]{
//                mensagem.getNomeCliente(),
//                mensagem.getQuemEnviou(),
//                mensagem.getMeio(),
//                mensagem.getConteudo(),
//                Main.getManager().transformarData(mensagem.getData()).replace("-", "às")
//                });
//        }


        jTMensagens.getColumnModel().getColumn(3).setCellRenderer(new WordWrapRenderer());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_consultar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTMensagens;
    private javax.swing.JLabel label_iconUsuario;
    private javax.swing.JLabel label_nomeCliente;
    private javax.swing.JLabel label_responsavelRegistro;
    private javax.swing.JTextField nomeClienteTextField;
    private javax.swing.JTextField nomeQuemEnviouTextField;
    // End of variables declaration//GEN-END:variables
}
