/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.GUI.mensagem;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import projeto.GUI.menu.MenuPrincipal;
import projeto.Main;
import projeto.model.MensagemColetiva;
import projeto.model.MensagemIndividual;
import projeto.model.Projeto;
import projeto.model.Usuario;
import projeto.model.tipos.FuncaoUsuario;

/**
 *
 * @author jenny
 */
public class ConsultarMensagem extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarMensagem
     */
    public ConsultarMensagem() {
        initComponents();
        DefaultTableModel tabelaMensagens =  (DefaultTableModel) tabelaTipoMensagem.getModel();
        tabelaTipoMensagem.setRowSorter(new TableRowSorter(tabelaMensagens));
         
        readTable();

        setTitle("Pro4Tech - Consultar mensagens");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaTipoMensagem = new javax.swing.JTable();
        comboBoxTipoMensagem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoMensagens = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        botaoRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tabelaTipoMensagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaTipoMensagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTipoMensagemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaTipoMensagem);
        if (tabelaTipoMensagem.getColumnModel().getColumnCount() > 0) {
            tabelaTipoMensagem.getColumnModel().getColumn(0).setResizable(false);
            tabelaTipoMensagem.getColumnModel().getColumn(1).setResizable(false);
        }

        comboBoxTipoMensagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Coletiva" }));
        comboBoxTipoMensagem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxTipoMensagemItemStateChanged(evt);
            }
        });

        jLabel1.setText("Tipo de mensagem:");

        campoMensagens.setEditable(false);
        campoMensagens.setColumns(20);
        campoMensagens.setLineWrap(true);
        campoMensagens.setRows(5);
        jScrollPane1.setViewportView(campoMensagens);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Histórico de mensagens");

        botaoRetornar.setText("Retornar");
        botaoRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoRetornar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxTipoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTipoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30)
                .addComponent(botaoRetornar)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRetornarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botaoRetornarActionPerformed

    private void comboBoxTipoMensagemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxTipoMensagemItemStateChanged
        // TODO add your handling code here:
        readTable();
    }//GEN-LAST:event_comboBoxTipoMensagemItemStateChanged

    private void tabelaTipoMensagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTipoMensagemMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = tabelaTipoMensagem.getSelectedRow();
        int id = Integer.parseInt(tabelaTipoMensagem.getValueAt(linhaSelecionada, 1) + "");
        String selecionado = comboBoxTipoMensagem.getSelectedItem() + "";
        
        if(selecionado.equalsIgnoreCase("Individual")){
            
            List<MensagemIndividual> mensagens = Main.getManager().getmIndiDAO().getMensagensPorRemetente(id);
            
            String string = "";
            for(MensagemIndividual mensagem : mensagens){
                Usuario remetente = Main.getManager().getUsuarioByID(id);
                string += "[" + Main.getManager().transformarData(mensagem.getData()) + "] " + remetente.getNome() + ": " + mensagem.getConteudo() + "\n";
            }
            
            campoMensagens.setText(string);
        }else{
            
            List<MensagemColetiva> mensagens = Main.getManager().getmColeDAO().getMensagensPorDestinatario(id);
            
            String string = "";
            for(MensagemColetiva mensagem : mensagens){
                string += "[" + Main.getManager().transformarData(mensagem.getData()) + "]: " + mensagem.getConteudo() + "\n";
            }
            
            campoMensagens.setText(string);
        }
    }//GEN-LAST:event_tabelaTipoMensagemMouseClicked

    
    public void readTable(){
        String selecionado = comboBoxTipoMensagem.getSelectedItem() + "";
        
        
        
        
        DefaultTableModel tabelaMensagens =  (DefaultTableModel) tabelaTipoMensagem.getModel();
        
         tabelaMensagens.setNumRows(0);
         
         if(selecionado.equalsIgnoreCase("Individual")){
             
             List<MensagemIndividual> listaMensagens = Main.getManager().getmIndiDAO().getMensagensPorDestinatario(Main.getManager().getUsuarioLogado().getId());
             
             
             for(MensagemIndividual mensagens : listaMensagens){
                 int idRemetente = mensagens.getIdRemetente();
                 Usuario remetente = Main.getManager().getUsuarioByID(idRemetente);
                 tabelaMensagens.addRow(new Object[]{
                        remetente.getNome(),
                        mensagens.getId()
                 });
             }
             
         }else{
             
             List<MensagemColetiva> listaMensagens = Main.getManager().getmColeDAO().getMensagensPorRemetente(Main.getManager().getUsuarioLogado().getId());
             
             for(MensagemColetiva mensagens : listaMensagens){
                 int idDest = mensagens.getIdDestinatario();
                 Projeto dest = Main.getManager().getProjetoDAO().getProjetoPorID(idDest);
                 tabelaMensagens.addRow(new Object[] {
                        dest.getNome(),
                        idDest
                 });
             }
         }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRetornar;
    private javax.swing.JTextArea campoMensagens;
    private javax.swing.JComboBox<String> comboBoxTipoMensagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaTipoMensagem;
    // End of variables declaration//GEN-END:variables
}
