/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.GUI.mensagem;

import javax.swing.JFrame;
import projeto.model.Mensagem;

/**
 *
 * @author jenny
 */
public class ExibirLinhasTabela extends javax.swing.JFrame {

    
    private Mensagem mensagem;
    
    public ExibirLinhasTabela(Mensagem mensagem) {
        initComponents();
        
        this.mensagem = mensagem;
        
//        nomeClienteTextField.setText(mensagem.getNomeCliente());
//        quemEnviouTextField.setText(mensagem.getQuemEnviou());
        meioTextField.setText(mensagem.getMeio());
        conteudo.setText(mensagem.getConteudo());

        
        setTitle("Pro4Tech - Exibindo mensagem");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meioTextField = new javax.swing.JTextField();
        label_meioEnvio = new javax.swing.JLabel();
        quemEnviouTextField = new javax.swing.JTextField();
        label_conteudo = new javax.swing.JLabel();
        label_nomeCliente = new javax.swing.JLabel();
        Button_cancelar = new javax.swing.JButton();
        nomeClienteTextField = new javax.swing.JTextField();
        label_responsavelRegistro = new javax.swing.JLabel();
        label_mensagemRegistrada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        conteudo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        meioTextField.setEditable(false);
        meioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meioTextFieldActionPerformed(evt);
            }
        });

        label_meioEnvio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_meioEnvio.setText("Meio de envio:");

        quemEnviouTextField.setEditable(false);
        quemEnviouTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quemEnviouTextFieldActionPerformed(evt);
            }
        });

        label_conteudo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_conteudo.setText("Conteúdo:");

        label_nomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_nomeCliente.setText("Nome do Cliente:");

        Button_cancelar.setText("Cancelar");
        Button_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cancelarActionPerformed(evt);
            }
        });

        nomeClienteTextField.setEditable(false);
        nomeClienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteTextFieldActionPerformed(evt);
            }
        });

        label_responsavelRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_responsavelRegistro.setText("Responsável pelo registro: ");

        label_mensagemRegistrada.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        label_mensagemRegistrada.setText("Mensagem Registrada");

        conteudo.setEditable(false);
        conteudo.setColumns(20);
        conteudo.setLineWrap(true);
        conteudo.setRows(5);
        jScrollPane1.setViewportView(conteudo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 179, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Button_cancelar)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_mensagemRegistrada)
                                .addGap(197, 197, 197))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label_responsavelRegistro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(quemEnviouTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label_nomeCliente)
                            .addGap(63, 63, 63)
                            .addComponent(nomeClienteTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label_conteudo)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label_meioEnvio)
                            .addGap(79, 79, 79)
                            .addComponent(meioTextField)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(label_mensagemRegistrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_cancelar)
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_nomeCliente)
                        .addComponent(nomeClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(quemEnviouTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_responsavelRegistro, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_meioEnvio)
                        .addComponent(meioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(label_conteudo)
                    .addGap(348, 348, 348)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meioTextFieldActionPerformed

    private void quemEnviouTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quemEnviouTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_quemEnviouTextFieldActionPerformed

    private void Button_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cancelarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_Button_cancelarActionPerformed

    private void nomeClienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_cancelar;
    private javax.swing.JTextArea conteudo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_conteudo;
    private javax.swing.JLabel label_meioEnvio;
    private javax.swing.JLabel label_mensagemRegistrada;
    private javax.swing.JLabel label_nomeCliente;
    private javax.swing.JLabel label_responsavelRegistro;
    private javax.swing.JTextField meioTextField;
    private javax.swing.JTextField nomeClienteTextField;
    private javax.swing.JTextField quemEnviouTextField;
    // End of variables declaration//GEN-END:variables
}
